### ISSUE TITLE
US:1. As a user, I want to create an account so that I can use the messaging application

### ISSUE THREAD

**Issue by mauleenn** [HowardPotts98/Internet-Programing-Project#1]
As a user, I want to create an account so that I can use the messaging application.
* An account is defined by a ...
  * username (must be unique)
  * password

The username and password will be stored in the database.

At the completion of the US the buttons (Create An Account and Login), fields (Username (unique) and Password fields), and the login page will be implemented.

**Comment by HowardPotts98** [comment]
This requirement is complete
